export const LIST_SCREENSHOTS = 'LinksPage/LIST_SCREENSHOTS';
export const LIST_SCREENSHOTS_SUCCESS = 'LinksPage/LIST_SCREENSHOTS_SUCCESS';
export const LIST_SCREENSHOTS_ERROR = 'LinksPage/LIST_SCREENSHOTS_ERROR';
